# -*- coding: utf-8 -*-
"""
PPT Generator for ROI Algorithm Pipeline Documentation (English Version).
Uses images from docs/images/ (generated by generate_images.py).
"""
import sys
from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

DOCS_DIR = Path(__file__).parent
IMG_DIR = DOCS_DIR / "images"

BLUE = RGBColor(0x00, 0x3C, 0x71)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
GRAY = RGBColor(0x33, 0x33, 0x33)


def _add_bg(slide, color):
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_text(slide, left, top, width, height, text, size=18, bold=False,
              color=GRAY, align=PP_ALIGN.LEFT, font_name="Calibri"):
    txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(size)
    p.font.bold = bold
    p.font.color.rgb = color
    p.font.name = font_name
    p.alignment = align
    return txBox


def _add_image(slide, img_path, left, top, width=None, height=None):
    kwargs = {}
    if width: kwargs['width'] = Inches(width)
    if height: kwargs['height'] = Inches(height)
    return slide.shapes.add_picture(str(img_path), Inches(left), Inches(top), **kwargs)


def _add_bullet_text(slide, left, top, width, height, lines, size=14, color=GRAY):
    txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    tf = txBox.text_frame
    tf.word_wrap = True
    for i, line in enumerate(lines):
        if i == 0:
            p = tf.paragraphs[0]
        else:
            p = tf.add_paragraph()
        p.text = line
        p.font.size = Pt(size)
        p.font.color.rgb = color
        p.font.name = "Calibri"
        p.space_after = Pt(4)
    return txBox


def create_ppt(pipeline_data=None):
    """Create English PPT"""
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # ═══════════════════════════════════════════
    # Slide 1: Title
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_bg(slide, BLUE)
    _add_text(slide, 1, 1.5, 11, 1.5,
              "ROI Algorithm Pipeline", size=44, bold=True, color=WHITE, align=PP_ALIGN.CENTER)
    _add_text(slide, 1, 3.2, 11, 1,
              "Display Panel Image Processing — Step-by-Step Analysis", size=24,
              color=RGBColor(0xBB, 0xDE, 0xFB), align=PP_ALIGN.CENTER)
    _add_text(slide, 1, 5.0, 11, 0.8,
              "Detailed Documentation Based on src/ Modules", size=18,
              color=RGBColor(0x90, 0xCA, 0xF9), align=PP_ALIGN.CENTER)
    _add_text(slide, 1, 6.0, 11, 0.5,
              "MR Display Hardware Team | Byung Geun Jun", size=14,
              color=RGBColor(0x64, 0xB5, 0xF6), align=PP_ALIGN.CENTER)

    # ═══════════════════════════════════════════
    # Slide 2: Pipeline Overview
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Pipeline Overview", size=32, bold=True, color=BLUE)
    _add_bullet_text(slide, 0.5, 1.2, 5.5, 5.5, [
        "End-to-End Pipeline Flow:",
        "",
        "Step 0: Load Original Image (1_utils.py)",
        "  \u2022 Read 16-bit TIF image (G32_cal.tif)",
        "",
        "Step 1: Image Cropping (3_image_cropper.py)",
        "  \u2022 Remove unnecessary border regions",
        "",
        "Step 2: ROI Detection (2_roi_detector.py)",
        "  \u2022 Binarization \u2192 Morphology \u2192 Contour \u2192 Corner extraction",
        "",
        "Step 3: Perspective Correction (4_perspective_warper.py)",
        "  \u2022 4-corner-based perspective transform",
        "",
        "Step 4: Area-Sum Resize (5_area_sum_resizer.py)",
        "  \u2022 Camera resolution \u2192 Display resolution conversion",
        "",
        "Step 5: Normalization (6_image_normalizer.py)",
        "  \u2022 Normalize to 16-bit range (0\u201365535)",
    ], size=12)
    img_path = IMG_DIR / "step6_arch.png"
    if img_path.exists():
        _add_image(slide, img_path, 6.5, 1.2, width=6.3)

    # ═══════════════════════════════════════════
    # Slide 3: Step 0 - Original Image
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Step 0: Load Original Image (1_utils.py)", size=28, bold=True, color=BLUE)
    _add_bullet_text(slide, 0.5, 1.2, 5, 2.5, [
        "\u25a0 Module: src/1_utils.py",
        "  \u2022 Load 16-bit TIF image via cv2.imread()",
        "  \u2022 BGR \u2192 RGB conversion (if needed)",
        "",
        "\u25a0 Input File: data/G32_cal.tif",
        "  \u2022 Display panel image captured by mono camera",
        "  \u2022 16-bit grayscale format",
    ], size=12)
    img_path = IMG_DIR / "step0_original.png"
    if img_path.exists():
        _add_image(slide, img_path, 5.8, 1.0, width=7)

    # ═══════════════════════════════════════════
    # Slide 4: Step 0 - Histogram
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Step 0: Original Image Analysis", size=28, bold=True, color=BLUE)
    img_path = IMG_DIR / "step0_histogram.png"
    if img_path.exists():
        _add_image(slide, img_path, 0.5, 1.2, width=12)
    _add_bullet_text(slide, 0.5, 5.8, 12, 1.5, [
        "\u2022 Histogram reveals the distribution of background (low values) vs. display area (high values)",
        "\u2022 Red dashed line: Threshold used for ROI detection (=50) \u2014 the binarization cutoff",
    ], size=12)

    # ═══════════════════════════════════════════
    # Slide 5: Step 1 - Image Cropping
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Step 1: Image Cropping (3_image_cropper.py)", size=28, bold=True, color=BLUE)
    img_path = IMG_DIR / "step1_crop.png"
    if img_path.exists():
        _add_image(slide, img_path, 0.3, 1.2, width=12.5)
    _add_bullet_text(slide, 0.5, 5.5, 12, 2, [
        "\u25a0 Classes: ImageCropper + CropRegion",
        "  \u2022 Crop region: (1700, 300) \u2192 (11700, 9900) \u2014 removes unnecessary border areas",
        "  \u2022 Implementation: numpy array slicing \u2014 image[y_start:y_end, x_start:x_end]",
        "  \u2022 Purpose: Speed up ROI detection + eliminate noise in border regions",
    ], size=12)

    # ═══════════════════════════════════════════
    # Slide 6: Step 2 - ROI Detection (Binarization)
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Step 2: ROI Detection \u2014 Binarization & Morphology (2_roi_detector.py)", size=24, bold=True, color=BLUE)
    img_path = IMG_DIR / "step2_binary.png"
    if img_path.exists():
        _add_image(slide, img_path, 0.3, 1.2, width=12.5)
    _add_bullet_text(slide, 0.5, 5.3, 12, 2, [
        "\u25a0 Class: ROIDetector",
        "  1) Binarization: pixel > threshold(50) \u2192 white, otherwise \u2192 black",
        "  2) Morphological Close (51\u00d751 kernel): Fill small holes in the binary mask",
        "  3) Morphological Open (51\u00d751 kernel): Remove small protrusions",
        "  4) scipy.ndimage.binary_fill_holes(): Fill remaining internal voids",
    ], size=12)

    # ═══════════════════════════════════════════
    # Slide 7: Step 2 - Contour & Corners
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Step 2: ROI Detection \u2014 Contour & Corner Extraction", size=24, bold=True, color=BLUE)
    img_path = IMG_DIR / "step2_corners.png"
    if img_path.exists():
        _add_image(slide, img_path, 0.3, 1.1, width=8.5)
    img_path2 = IMG_DIR / "step2_table.png"
    if img_path2.exists():
        _add_image(slide, img_path2, 9.0, 1.1, width=4)
    _add_bullet_text(slide, 0.5, 5.3, 12, 2, [
        "\u25a0 Algorithm:",
        "  1) cv2.findContours() \u2192 Extract external contours from binary mask",
        "  2) max(contours, key=cv2.contourArea) \u2192 Select the largest contour (display panel)",
        "  3) cv2.minAreaRect() + cv2.boxPoints() \u2192 Compute 4 corners of minimum-area rotated rect",
        "  4) Corner ordering: Sort by sum/diff to arrange as TL, TR, BR, BL",
        "  5) Tilt angle: arctan2(top_edge_dy, top_edge_dx) for rotation measurement",
    ], size=12)

    # ═══════════════════════════════════════════
    # Slide 8: Step 3 - Perspective Warp
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Step 3: Perspective Correction (4_perspective_warper.py)", size=28, bold=True, color=BLUE)
    img_path = IMG_DIR / "step3_warp.png"
    if img_path.exists():
        _add_image(slide, img_path, 0.3, 1.1, width=8)
    _add_bullet_text(slide, 8.5, 1.2, 4.5, 3.5, [
        "\u25a0 Class: PerspectiveWarper",
        "",
        "Core Operations:",
        "  1) Map 4 source corners \u2192 4 dest corners",
        "     (rectified rectangle)",
        "  2) cv2.getPerspectiveTransform()",
        "     \u2192 Compute 3\u00d73 homography matrix",
        "  3) cv2.warpPerspective()",
        "     \u2192 Apply the perspective transform",
        "",
        "\u25a0 Interpolation: INTER_NEAREST",
        "  \u2022 Nearest-neighbor interpolation",
        "  \u2022 Preserves original pixel values (critical!)",
        "  \u2022 Maintains measurement accuracy",
    ], size=11)

    # ═══════════════════════════════════════════
    # Slide 9: Step 3 - Transform Details
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Step 3: Transform Matrix & Corner Mapping Details", size=28, bold=True, color=BLUE)
    img_path = IMG_DIR / "step3_matrix.png"
    if img_path.exists():
        _add_image(slide, img_path, 1.5, 1.2, width=10)
    _add_bullet_text(slide, 0.5, 5.5, 12, 1.5, [
        "\u2022 3\u00d73 homography matrix maps tilted quadrilateral corners to an axis-aligned rectangle",
        "\u2022 INTER_NEAREST interpolation ensures original measurement pixel values are exactly preserved",
    ], size=12)

    # ═══════════════════════════════════════════
    # Slide 10: Step 4 - Area Sum Resize
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Step 4: Area-Sum Resize (5_area_sum_resizer.py)", size=24, bold=True, color=BLUE)
    img_path = IMG_DIR / "step4_resize.png"
    if img_path.exists():
        _add_image(slide, img_path, 0.3, 1.1, width=12.5)
    _add_bullet_text(slide, 0.5, 5.3, 12, 2, [
        "\u25a0 Class: AreaSumResizer \u2014 Camera resolution \u2192 Display resolution conversion",
        "  \u2022 Computes the mean of all camera pixels corresponding to each display pixel",
        "  \u2022 Not a simple downsampling \u2014 an area-based summation that considers every camera pixel",
        "  \u2022 Output: 2412 \u00d7 2288 (1:1 mapping to actual display resolution)",
    ], size=12)

    # ═══════════════════════════════════════════
    # Slide 11: Step 4 - Concept
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Step 4: Area-Sum Resize \u2014 Concept Diagram", size=28, bold=True, color=BLUE)
    img_path = IMG_DIR / "step4_concept.png"
    if img_path.exists():
        _add_image(slide, img_path, 0.3, 1.1, width=7)
    _add_bullet_text(slide, 7.5, 1.2, 5.3, 5, [
        "\u25a0 Area-Sum Resize Principle:",
        "",
        "In the camera image, one display pixel",
        "corresponds to approximately 3.5\u00d73.5",
        "camera pixels.",
        "",
        "The output value for each display pixel",
        "is the mean of all camera pixels within",
        "the corresponding area.",
        "",
        "\u25a0 Why Area-Sum?",
        "  \u2022 Standard resize (bilinear, etc.) alters",
        "    original measurement values via interpolation",
        "  \u2022 Area-Sum directly averages all pixels in the",
        "    corresponding area \u2192 preserves accuracy",
        "  \u2022 Essential for obtaining precise sub-pixel",
        "    brightness values in display measurement",
    ], size=11)

    # ═══════════════════════════════════════════
    # Slide 12: Step 4 - Zoom Compare
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Step 4: Zoom Comparison \u2014 Camera vs. Display Resolution", size=24, bold=True, color=BLUE)
    img_path = IMG_DIR / "step4_zoom.png"
    if img_path.exists():
        _add_image(slide, img_path, 0.3, 1.1, width=12.5)
    _add_bullet_text(slide, 0.5, 5.5, 12, 1.5, [
        "\u2022 Left: Warped image center 100\u00d7100 region \u2014 individual camera pixels visible",
        "\u2022 Right: Resized image center 30\u00d730 region \u2014 each pixel maps to one display pixel",
    ], size=12)

    # ═══════════════════════════════════════════
    # Slide 13: Step 5 - Normalization
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Step 5: 16-bit Normalization (6_image_normalizer.py)", size=28, bold=True, color=BLUE)
    img_path = IMG_DIR / "step5_norm.png"
    if img_path.exists():
        _add_image(slide, img_path, 0.3, 1.1, width=12.5)
    _add_bullet_text(slide, 0.5, 6.2, 12, 1, [
        "\u25a0 Formula: output = (pixel - min) / (max - min) \u00d7 65535  |  "
        "Class: ImageNormalizer (bit_depth=16)",
    ], size=12)

    # ═══════════════════════════════════════════
    # Slide 14: Step 6 - Pipeline Summary
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Full Pipeline Summary", size=32, bold=True, color=BLUE)
    img_path = IMG_DIR / "step6_summary.png"
    if img_path.exists():
        _add_image(slide, img_path, 0.3, 1.2, width=12.5)
    _add_bullet_text(slide, 0.5, 4.5, 12, 2.5, [
        "Original \u2192 Crop \u2192 ROI Detect \u2192 Perspective Warp \u2192 Area-Sum Resize \u2192 16-bit Normalize",
        "",
        "\u25a0 Key Design Principles:",
        "  \u2022 INTER_NEAREST interpolation: Preserves original pixel values (measurement accuracy)",
        "  \u2022 Area-Sum resize: Every camera pixel is accounted for in the summation",
        "  \u2022 Modular OOP architecture: Each step is an independent class, orchestrated by",
        "    7_display_panel_processor.py (DisplayPanelProcessor)",
    ], size=13)

    # ═══════════════════════════════════════════
    # Slide 15: Code Structure
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(slide, 0.5, 0.3, 12, 0.8,
              "Code Structure (src/ Directory)", size=32, bold=True, color=BLUE)
    _add_bullet_text(slide, 0.5, 1.3, 6, 5.5, [
        "src/",
        "\u251c\u2500\u2500 __init__.py              Package init & re-exports",
"\u251c\u2500\u2500 1_utils.py               Utilities (load/save/draw)",
        "\u251c\u2500\u2500 2_roi_detector.py        ROI detection classes",
        "\u2502     \u251c\u2500\u2500 ROIDetector           Basic detector",
        "\u2502     \u2514\u2500\u2500 AdaptiveROIDetector   Adaptive detector",
        "\u251c\u2500\u2500 3_image_cropper.py       Image cropping",
        "\u2502     \u251c\u2500\u2500 CropRegion            Crop region definition",
        "\u2502     \u2514\u2500\u2500 ImageCropper          Crop execution",
        "\u251c\u2500\u2500 4_perspective_warper.py  Perspective correction",
        "\u2502     \u2514\u2500\u2500 PerspectiveWarper     Warp execution",
        "\u251c\u2500\u2500 5_area_sum_resizer.py    Area-sum resize",
        "\u2502     \u2514\u2500\u2500 AreaSumResizer        Resize execution",
        "\u251c\u2500\u2500 6_image_normalizer.py    Normalization",
        "\u2502     \u2514\u2500\u2500 ImageNormalizer       8/16-bit conversion",
        "\u2514\u2500\u2500 7_display_panel_processor.py   Pipeline integration",
        "      \u251c\u2500\u2500 ProcessingConfig      Configuration management",
        "      \u251c\u2500\u2500 ProcessingResult      Result container",
        "      \u2514\u2500\u2500 DisplayPanelProcessor Main orchestrator",
    ], size=11)
    img_path = IMG_DIR / "step6_arch.png"
    if img_path.exists():
        _add_image(slide, img_path, 6.8, 1.3, width=6)

    # ═══════════════════════════════════════════
    # Slide 16: Thank You
    # ═══════════════════════════════════════════
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_bg(slide, BLUE)
    _add_text(slide, 1, 2.5, 11, 1.5,
              "Thank You", size=48, bold=True, color=WHITE, align=PP_ALIGN.CENTER)
    _add_text(slide, 1, 4.2, 11, 1,
              "ROI Algorithm Pipeline Documentation", size=20,
              color=RGBColor(0xBB, 0xDE, 0xFB), align=PP_ALIGN.CENTER)
    _add_text(slide, 1, 5.5, 11, 0.5,
              "Generated from src/ modules | MR Display Hardware Team", size=14,
              color=RGBColor(0x90, 0xCA, 0xF9), align=PP_ALIGN.CENTER)

    # Save PPT
    ppt_path = DOCS_DIR / "ROI_Pipeline_Documentation.pptx"
    prs.save(str(ppt_path))
    print(f"\nPPT saved: {ppt_path}")
    return str(ppt_path)


if __name__ == "__main__":
    create_ppt()
