# -*- coding: utf-8 -*-
"""
Word Document (DOCX) User Manual Generator for ROI Algorithm Pipeline.
Uses images from docs/images/ (generated by generate_images.py).

Usage:
    python docs/create_user_manual_doc.py

Requires:
    pip install python-docx
"""
import sys
from pathlib import Path

try:
    from docx import Document
    from docx.shared import Inches, Pt, Cm, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
except ImportError:
    print("Error: python-docx is required. Install with: pip install python-docx")
    sys.exit(1)

PROJECT_ROOT = Path(__file__).parent.parent
DOCS_DIR = Path(__file__).parent
IMG_DIR = DOCS_DIR / "images"

BLUE = RGBColor(0x00, 0x3C, 0x71)
DARK_GRAY = RGBColor(0x33, 0x33, 0x33)


def _add_heading(doc, text, level=1):
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.color.rgb = BLUE
    return h


def _add_para(doc, text, bold=False, size=11, color=None, alignment=None):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(size)
    if bold:
        run.bold = True
    if color:
        run.font.color.rgb = color
    if alignment:
        p.alignment = alignment
    return p


def _add_bullet(doc, text, bold_prefix=None):
    p = doc.add_paragraph(style='List Bullet')
    if bold_prefix:
        run = p.add_run(bold_prefix)
        run.bold = True
        run.font.size = Pt(10)
        run = p.add_run(text)
        run.font.size = Pt(10)
    else:
        run = p.add_run(text)
        run.font.size = Pt(10)
    return p


def _add_code(doc, code, title=None):
    if title:
        _add_para(doc, title, bold=True, size=10)
    p = doc.add_paragraph()
    run = p.add_run(code)
    run.font.name = 'Consolas'
    run.font.size = Pt(9)
    run.font.color.rgb = DARK_GRAY
    pf = p.paragraph_format
    pf.left_indent = Cm(1)
    pf.space_before = Pt(4)
    pf.space_after = Pt(4)
    return p


def _add_image(doc, img_name, width=6, caption=None):
    img_path = IMG_DIR / img_name
    if not img_path.exists():
        _add_para(doc, f"[Image not found: {img_name}]",
                  color=RGBColor(0xFF, 0x00, 0x00), size=9)
        return
    doc.add_picture(str(img_path), width=Inches(width))
    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
    if caption:
        cap = doc.add_paragraph()
        cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = cap.add_run(caption)
        run.font.size = Pt(9)
        run.font.italic = True
        run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)


def _add_table(doc, headers, rows):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.style = 'Light List Accent 1'
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    for i, header in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = header
        for p in cell.paragraphs:
            for run in p.runs:
                run.font.bold = True
                run.font.size = Pt(10)
    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.rows[r_idx + 1].cells[c_idx]
            cell.text = str(val)
            for p in cell.paragraphs:
                for run in p.runs:
                    run.font.size = Pt(10)
    doc.add_paragraph()
    return table


# ═══════════════════════════════════════════════════════════════
# Section builders
# ═══════════════════════════════════════════════════════════════

def build_title_page(doc):
    for _ in range(6):
        doc.add_paragraph()
    t = doc.add_paragraph()
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = t.add_run("ROI Algorithm Pipeline")
    r.font.size = Pt(36); r.font.color.rgb = BLUE; r.bold = True

    s = doc.add_paragraph()
    s.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = s.add_run("User Manual")
    r.font.size = Pt(28); r.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    doc.add_paragraph()
    d = doc.add_paragraph()
    d.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = d.add_run("Display Panel Image Processing Tool")
    r.font.size = Pt(16); r.font.color.rgb = DARK_GRAY

    doc.add_paragraph()
    i = doc.add_paragraph()
    i.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = i.add_run(
        "Version 1.0.0\n\n"
        "Byung Geun (BG) Jun\n"
        "Display Algorithm Architect\n"
        "MR Display Hardware Team\n\n"
        "April 2026"
    )
    r.font.size = Pt(12); r.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
    doc.add_page_break()


def build_toc(doc):
    _add_heading(doc, "Table of Contents", level=1)
    items = [
        ("1. Introduction", True),
        ("2. System Requirements & Installation", True),
        ("3. Quick Start Guide", True),
        ("4. Pipeline Overview", True),
        ("5. Step-by-Step Walkthrough", True),
        ("   5.0 Load Original Image", False),
        ("   5.1 Image Cropping", False),
        ("   5.2 ROI Detection", False),
        ("   5.3 Perspective Correction", False),
        ("   5.4 Area-Sum Resize", False),
        ("   5.5 16-bit Normalization", False),
        ("6. Configuration Reference", True),
        ("7. Python API Reference", True),
        ("8. Output Files", True),
        ("9. Troubleshooting & FAQ", True),
    ]
    for text, bold in items:
        p = doc.add_paragraph()
        r = p.add_run(text)
        r.font.size = Pt(11)
        if bold:
            r.bold = True
    doc.add_page_break()


def build_section1(doc):
    _add_heading(doc, "1. Introduction", level=1)
    _add_heading(doc, "What is This Tool?", level=2)
    _add_para(doc,
        "The ROI Algorithm Pipeline is a Python-based image processing tool designed "
        "for display panel analysis. It takes a raw camera image of a display panel "
        "(captured by a mono camera) and produces a clean, normalized image at "
        "display-pixel resolution.")

    _add_heading(doc, "What Does It Do?", level=2)
    _add_para(doc, "The tool performs the following operations automatically:")
    for i, (pref, txt) in enumerate([
        ("Crops ", "the image to remove unnecessary borders"),
        ("Detects ", "the display panel region (ROI) in the camera image"),
        ("Corrects ", "perspective distortion (tilt)"),
        ("Resizes ", "from camera resolution to display resolution using area-sum averaging"),
        ("Normalizes ", "the output to 16-bit dynamic range"),
    ], 1):
        _add_bullet(doc, txt, bold_prefix=f"{i}. {pref}")

    _add_heading(doc, "Key Features", level=2)
    _add_table(doc,
        ["Feature", "Description"],
        [
            ["Automatic ROI Detection", "No manual corner selection needed"],
            ["Pixel Value Preservation", "INTER_NEAREST interpolation - no data blending"],
            ["Area-Sum Resize", "Every camera pixel contributes to the output"],
            ["16-bit Output", "Full dynamic range for precise analysis"],
            ["Modular Design", "Each step can be used independently"],
        ])
    doc.add_page_break()


def build_section2(doc):
    _add_heading(doc, "2. System Requirements & Installation", level=1)

    _add_heading(doc, "Prerequisites", level=2)
    _add_bullet(doc, "Python 3.8 or higher")
    _add_bullet(doc, "Windows, macOS, or Linux")
    _add_bullet(doc, "Input Image: 16-bit TIF format (mono camera capture)")

    _add_heading(doc, "Step 1: Install Python Dependencies", level=2)
    _add_para(doc, "Open a terminal and navigate to the project folder:")
    _add_code(doc, "cd 20260304_ROI_algorithm\npip install -r requirements.txt")
    _add_para(doc, "Required packages:")
    _add_code(doc, "numpy>=1.21.0\nopencv-python>=4.5.0\nmatplotlib>=3.4.0\nscipy>=1.7.0\npillow>=8.0.0")

    _add_heading(doc, "Step 2: Install Optional Dependencies", level=2)
    _add_para(doc, "For faster processing (recommended):")
    _add_code(doc, "pip install numba")
    _add_para(doc, "For documentation generation:")
    _add_code(doc, "pip install python-pptx python-docx")

    _add_heading(doc, "Step 3: Verify Installation", level=2)
    _add_code(doc, 'python -c "import cv2, numpy, scipy, matplotlib; print(\'All OK\')"')

    _add_heading(doc, "Project Folder Structure", level=2)
    _add_code(doc,
        "20260304_ROI_algorithm/\n"
        "+-- src/                          # Core pipeline modules\n"
        "|   +-- __init__.py               # Package exports\n"
        "|   +-- 1_utils.py                # Utility functions\n"
        "|   +-- 2_roi_detector.py         # ROI detection\n"
        "|   +-- 3_image_cropper.py        # Image cropping\n"
        "|   +-- 4_perspective_warper.py   # Tilt correction\n"
        "|   +-- 5_area_sum_resizer.py     # Area-sum resize\n"
        "|   +-- 6_image_normalizer.py     # 16-bit normalization\n"
        "|   +-- 7_display_panel_processor.py  # Pipeline orchestrator\n"
        "|   +-- main.py                   # CLI entry point\n"
        "+-- data/                         # Input images\n"
        "+-- output/                       # Generated output files\n"
        "+-- docs/                         # Documentation\n"
        "+-- requirements.txt              # Python dependencies")
    doc.add_page_break()


def build_section3(doc):
    _add_heading(doc, "3. Quick Start Guide", level=1)

    _add_heading(doc, "Run with Default Settings (Fastest Way)", level=2)
    _add_code(doc, "python src/main.py")
    _add_para(doc, "This processes data/G32_cal.tif with default settings and saves to output/.")

    _add_heading(doc, "Expected Console Output", level=2)
    _add_code(doc,
        "============================================================\n"
        "Display Panel Processing Pipeline\n"
        "============================================================\n"
        "[Step 1] Loading image...\n"
        "  Original image: 14144 x 10640 pixels\n"
        "[Step 2] Cropping image...\n"
        "  Cropped image: 10000 x 9600 pixels\n"
        "[Step 3] Detecting ROI...\n"
        "  Detected ROI: 9374 x 8894 pixels\n"
        "  Tilt angle: -0.03 degrees\n"
        "[Step 4] Applying perspective warp...\n"
        "[Step 5] Resizing to display resolution...\n"
        "  Target size: 2412 x 2288 pixels\n"
        "[Step 6] Normalizing to 16-bit...\n"
        "============================================================\n"
        "Processing Complete!\n"
        "============================================================")

    _add_heading(doc, "Common Command Examples", level=2)
    examples = [
        ("Use a different input image:", "python src/main.py --input path/to/image.tif"),
        ("Save output to a different folder:", "python src/main.py --output results/"),
        ("Set custom display resolution:", "python src/main.py --width 1920 --height 1080"),
        ("Adjust ROI detection threshold:", "python src/main.py --threshold 100"),
        ("Skip image cropping:", "python src/main.py --no-crop"),
        ("Full example with all options:",
         "python src/main.py ^\n"
         "    --input data/G32_cal.tif ^\n"
         "    --output output/ ^\n"
         "    --width 2412 --height 2288 ^\n"
         "    --threshold 50"),
    ]
    for title, cmd in examples:
        _add_para(doc, title, bold=True, size=10)
        _add_code(doc, cmd)
    doc.add_page_break()


def build_section4(doc):
    _add_heading(doc, "4. Pipeline Overview", level=1)
    _add_para(doc, "The processing pipeline transforms a raw camera image through 5 stages:")
    _add_code(doc,
        "Original Image (14144x10640, 16-bit)\n"
        "        |\n"
        "Step 1: Crop -> (10000x9600)\n"
        "        |\n"
        "Step 2: ROI Detection -> corners + tilt angle\n"
        "        |\n"
        "Step 3: Perspective Warp -> straightened image\n"
        "        |\n"
        "Step 4: Area-Sum Resize -> (2412x2288)\n"
        "        |\n"
        "Step 5: 16-bit Normalize -> [0, 65535]")

    _add_heading(doc, "Pipeline Summary Visualization", level=2)
    _add_image(doc, "step6_summary.png", width=6.2,
               caption="Figure 1: All 5 stages from original to final output")

    _add_heading(doc, "Architecture Diagram", level=2)
    _add_image(doc, "step6_arch.png", width=5.5,
               caption="Figure 2: Module architecture - each box is an independent Python class")
    doc.add_page_break()


def build_section5(doc):
    _add_heading(doc, "5. Step-by-Step Walkthrough", level=1)

    # Step 0
    _add_heading(doc, "5.0 Load Original Image", level=2)
    _add_para(doc, "The pipeline starts by loading the 16-bit TIF image captured by the mono camera.")
    _add_para(doc, "Module: src/1_utils.py", bold=True, size=10)
    _add_image(doc, "step0_original.png", width=5.5,
               caption="Figure 3: Original camera capture - 14144x10640 pixels, 16-bit grayscale")
    _add_para(doc, "The histogram shows pixel value distribution. Red dashed line = ROI threshold:")
    _add_image(doc, "step0_histogram.png", width=6.0,
               caption="Figure 4: Pixel histogram with threshold marker (red dashed = 50)")
    doc.add_page_break()

    # Step 1
    _add_heading(doc, "5.1 Image Cropping", level=2)
    _add_para(doc, "Removes unnecessary border regions to speed up processing.")
    _add_para(doc, "Module: src/3_image_cropper.py | Classes: ImageCropper, CropRegion", bold=True, size=10)
    _add_image(doc, "step1_crop.png", width=6.2,
               caption="Figure 5: Left = Original with crop region (red), Right = Cropped result")
    _add_bullet(doc, "Default crop region: (1700, 300) -> (11700, 9900)")
    _add_bullet(doc, "Original: 14144 x 10640  ->  Cropped: 10000 x 9600")
    _add_code(doc,
        "from src import ImageCropper, CropRegion\n\n"
        "cropper = ImageCropper(CropRegion(1700, 300, 11700, 9900))\n"
        "cropped = cropper.crop(image)\n"
        'print(f"Cropped: {cropped.shape[1]} x {cropped.shape[0]}")',
        title="Code Example:")
    doc.add_page_break()

    # Step 2
    _add_heading(doc, "5.2 ROI Detection", level=2)
    _add_para(doc, "Automatically finds the display panel boundary in the cropped image.")
    _add_para(doc, "Module: src/2_roi_detector.py | Class: ROIDetector", bold=True, size=10)
    _add_para(doc, "Algorithm:", bold=True)
    _add_bullet(doc, "Binarize - Pixels above threshold -> white, below -> black")
    _add_bullet(doc, "Morphological close (51x51 kernel) - Fills small holes")
    _add_bullet(doc, "Morphological open (51x51 kernel) - Removes protrusions")
    _add_bullet(doc, "Hole fill - scipy.ndimage.binary_fill_holes()")
    _add_bullet(doc, "Find contours - Extracts the largest contour")
    _add_bullet(doc, "Min area rect - Computes 4 ordered corners (TL, TR, BR, BL)")
    _add_image(doc, "step2_binary.png", width=6.2,
               caption="Figure 6: Binarization - Grayscale -> Binary -> Morphology + Hole Fill")
    _add_image(doc, "step2_corners.png", width=6.0,
               caption="Figure 7: Detected contour (green) and corners (TL=red, TR=green, BR=blue, BL=orange)")
    _add_image(doc, "step2_table.png", width=3.5,
               caption="Figure 8: Corner coordinates and ROI dimensions")
    _add_code(doc,
        "from src import ROIDetector\n\n"
        "detector = ROIDetector(threshold=50, morph_kernel_size=51)\n"
        "roi = detector.detect(cropped_image)\n\n"
        "if roi is not None:\n"
        '    print(f"Corners: {roi.corners}")\n'
        '    print(f"Tilt angle: {roi.angle:.4f} deg")\n'
        '    print(f"Size: {roi.width:.0f} x {roi.height:.0f}")',
        title="Code Example:")
    doc.add_page_break()

    # Step 3
    _add_heading(doc, "5.3 Perspective Correction", level=2)
    _add_para(doc, "Corrects tilt using a perspective transform.")
    _add_para(doc, "Module: src/4_perspective_warper.py | Class: PerspectiveWarper", bold=True, size=10)
    _add_para(doc,
        "Key feature: Uses INTER_NEAREST interpolation to preserve original pixel values. "
        "This is critical for measurement accuracy - bilinear/bicubic would blend values.")
    _add_image(doc, "step3_warp.png", width=6.2,
               caption="Figure 9: Before warp (tilted) vs. After warp (straightened)")
    _add_image(doc, "step3_matrix.png", width=5.5,
               caption="Figure 10: 3x3 perspective transform matrix and corner mapping")
    _add_code(doc,
        "from src import PerspectiveWarper\n"
        "import cv2\n\n"
        "warper = PerspectiveWarper(interpolation=cv2.INTER_NEAREST)\n"
        "warp_result = warper.warp(cropped, roi.corners)\n"
        "warped_image = warp_result.image\n"
        'print(f"Size: {warp_result.width} x {warp_result.height}")',
        title="Code Example:")
    doc.add_page_break()

    # Step 4
    _add_heading(doc, "5.4 Area-Sum Resize", level=2)
    _add_para(doc, "Converts camera-resolution image to display-pixel resolution.")
    _add_para(doc, "Module: src/5_area_sum_resizer.py | Class: AreaSumResizer", bold=True, size=10)
    _add_image(doc, "step4_resize.png", width=6.2,
               caption="Figure 11: Camera resolution (left) vs. Display resolution (right)")
    _add_para(doc, "How it works:", bold=True)
    _add_para(doc,
        "Each display pixel corresponds to ~3.89 x 3.89 camera pixels. "
        "Area-Sum computes a weighted average of ALL camera pixels within each "
        "display pixel's footprint, preserving total light energy.")
    _add_image(doc, "step4_concept.png", width=5.5,
               caption="Figure 12: Area-Sum concept - multiple camera pixels -> one display pixel")
    _add_para(doc, "Why Area-Sum instead of standard resize?", bold=True)
    _add_bullet(doc, "Standard resize (bilinear/bicubic) ALTERS values via interpolation")
    _add_bullet(doc, "Area-Sum PRESERVES total light energy - every pixel contributes")
    _add_bullet(doc, "Essential for accurate display measurement data")
    _add_image(doc, "step4_zoom.png", width=5.5,
               caption="Figure 13: Zoom - Camera pixels (100x100) vs Display pixels (30x30)")
    _add_code(doc,
        "from src import AreaSumResizer\n\n"
        "resizer = AreaSumResizer(show_progress=True)\n"
        "result = resizer.resize(warped_image, (2412, 2288))\n"
        'print(f"Scale X: {result.scale_x:.4f}")\n'
        'print(f"Scale Y: {result.scale_y:.4f}")',
        title="Code Example:")
    doc.add_page_break()

    # Step 5
    _add_heading(doc, "5.5 16-bit Normalization", level=2)
    _add_para(doc, "Maps output pixel values to the full 16-bit range [0, 65535].")
    _add_para(doc, "Module: src/6_image_normalizer.py | Class: ImageNormalizer", bold=True, size=10)
    _add_para(doc, "Formula: output = (pixel - min) / (max - min) x 65535", bold=True)
    _add_image(doc, "step5_norm.png", width=6.0,
               caption="Figure 14: Histogram before/after, output image, and formula details")
    _add_code(doc,
        "from src import ImageNormalizer\n\n"
        "normalizer = ImageNormalizer(bit_depth=16)\n"
        "result = normalizer.normalize(resized_image)\n"
        'print(f"Input range:  [{result.original_min:.2f}, {result.original_max:.2f}]")\n'
        'print(f"Output range: [{result.normalized_min}, {result.normalized_max}]")\n\n'
        "# Quick conversions\n"
        "img_16bit = normalizer.normalize_to_16bit(image)\n"
        "img_8bit  = normalizer.normalize_to_8bit(image)",
        title="Code Example:")
    doc.add_page_break()


def build_section6(doc):
    _add_heading(doc, "6. Configuration Reference", level=1)

    _add_heading(doc, "CLI Options", level=2)
    _add_table(doc,
        ["Option", "Short", "Default", "Description"],
        [
            ["--input", "-i", "data/G32_cal.tif", "Input image path"],
            ["--output", "-o", "output", "Output directory"],
            ["--width", "-W", "2412", "Target display width"],
            ["--height", "-H", "2288", "Target display height"],
            ["--threshold", "-t", "50", "ROI detection threshold"],
            ["--crop-x-start", "", "1700", "Crop X start"],
            ["--crop-y-start", "", "300", "Crop Y start"],
            ["--crop-x-end", "", "11700", "Crop X end"],
            ["--crop-y-end", "", "9900", "Crop Y end"],
            ["--no-crop", "", "(off)", "Disable cropping"],
            ["--no-intermediates", "", "(off)", "Skip intermediate files"],
        ])

    _add_heading(doc, "ProcessingConfig Parameters (Python API)", level=2)
    _add_code(doc,
        "from src import ProcessingConfig\n\n"
        "config = ProcessingConfig(\n"
        "    crop_x_start=1700,     # X start of crop region\n"
        "    crop_y_start=300,      # Y start of crop region\n"
        "    crop_x_end=11700,      # X end of crop region\n"
        "    crop_y_end=9900,       # Y end of crop region\n"
        "    use_crop=True,         # Enable/disable cropping\n"
        "    roi_threshold=50,      # Binarization threshold\n"
        "    morph_kernel_size=51,  # Morphological kernel size\n"
        "    display_width=2412,    # Target display width\n"
        "    display_height=2288,   # Target display height\n"
        "    output_bit_depth=16,   # Output bit depth (8 or 16)\n"
        "    save_intermediates=True # Save intermediate files\n"
        ")")

    _add_heading(doc, "How to Choose the Right Threshold", level=2)
    _add_table(doc,
        ["Threshold", "When to Use"],
        [
            ["30-50", "Low-brightness display panels or dim captures"],
            ["50-100", "Standard display panels (default: 50)"],
            ["100-200", "High-brightness panels with clear boundaries"],
            ["200+", "Very bright panels with strong background noise"],
        ])
    _add_para(doc,
        "Tip: Check the histogram of your image. The threshold should sit in the "
        "valley between the background peak and the display peak.", size=10)
    doc.add_page_break()


def build_section7(doc):
    _add_heading(doc, "7. Python API Reference", level=1)

    _add_heading(doc, "Full Pipeline (Recommended)", level=2)
    _add_code(doc,
        "from src import DisplayPanelProcessor, ProcessingConfig\n\n"
        "# Configure\n"
        "config = ProcessingConfig(display_width=2412, display_height=2288)\n\n"
        "# Create processor and run\n"
        "processor = DisplayPanelProcessor(config)\n"
        'result = processor.process("data/G32_cal.tif")\n\n'
        "# Save results\n"
        'processor.save_results(result, "output/")\n'
        'processor.save_visualization(result, "output/")\n\n'
        "# Access results\n"
        'print(f"Original:   {result.original_image.shape}")\n'
        'print(f"Tilt angle: {result.stats[\'tilt_angle\']:.4f} deg")')

    _add_heading(doc, "Using Individual Modules", level=2)
    _add_code(doc,
        "import cv2\n"
        "from src import (\n"
        "    ImageCropper, CropRegion, ROIDetector,\n"
        "    PerspectiveWarper, AreaSumResizer, ImageNormalizer\n"
        ")\n\n"
        "# Load\n"
        'image = cv2.imread("data/G32_cal.tif", cv2.IMREAD_UNCHANGED)\n\n'
        "# 1. Crop\n"
        "cropped = ImageCropper(CropRegion(1700,300,11700,9900)).crop(image)\n\n"
        "# 2. Detect ROI\n"
        "roi = ROIDetector(threshold=50).detect(cropped)\n\n"
        "# 3. Perspective warp\n"
        "warped = PerspectiveWarper(cv2.INTER_NEAREST).warp(cropped, roi.corners).image\n\n"
        "# 4. Area-sum resize\n"
        "resized = AreaSumResizer().resize(warped, (2412, 2288)).image\n\n"
        "# 5. Normalize\n"
        "final = ImageNormalizer(bit_depth=16).normalize(resized).image\n\n"
        "# Save\n"
        'cv2.imwrite("final_output.tif", final)')

    _add_heading(doc, "Adaptive ROI Detector (Advanced)", level=2)
    _add_para(doc, "For images with varying edge contrast across corners:")
    _add_code(doc,
        "from src import AdaptiveROIDetector\n\n"
        "detector = AdaptiveROIDetector(\n"
        "    initial_threshold=200,\n"
        "    corner_region_size=60,\n"
        "    threshold_range=(50, 600),\n"
        "    display_pixel_pitch=(3.5, 3.5),\n"
        "    align_to_display_grid=True\n"
        ")\n\n"
        "roi = detector.detect_with_grid_alignment(cropped)\n"
        "print(detector.get_corner_thresholds())")
    doc.add_page_break()


def build_section8(doc):
    _add_heading(doc, "8. Output Files", level=1)
    _add_table(doc,
        ["File", "Description", "Format"],
        [
            ["00_cropped_image.tif", "Cropped region from original", "16-bit TIF"],
            ["04_warped_image.tif", "Perspective-corrected image", "16-bit TIF"],
            ["05_resized_image.tif", "Area-sum resized to display res", "16-bit TIF"],
            ["06_final_normalized.tif", "Main output - 16-bit normalized", "16-bit TIF"],
            ["06_final_normalized_preview.png", "8-bit preview for quick viewing", "8-bit PNG"],
            ["06_final_comparison.png", "Side-by-side comparison", "PNG"],
        ])

    _add_heading(doc, "How to View the Output", level=2)
    _add_para(doc,
        "16-bit TIF files cannot be viewed in standard image viewers (they appear "
        "black or white). Use one of these methods:")
    _add_bullet(doc, "ImageJ/FIJI: Open -> Auto Brightness/Contrast")
    _add_bullet(doc, 'Python: cv2.imread("file.tif", cv2.IMREAD_UNCHANGED)')
    _add_bullet(doc, "MATLAB: imread('file.tif')")
    _add_para(doc,
        "The PNG preview (06_final_normalized_preview.png) is the quick-viewing "
        "option - it can be opened in any image viewer.")
    doc.add_page_break()


def build_section9(doc):
    _add_heading(doc, "9. Troubleshooting & FAQ", level=1)

    issues = [
        ("'No ROI detected' error",
         "The threshold is too high or too low for your image.",
         "Try different threshold values:\n"
         "python src/main.py --threshold 30\n"
         "python src/main.py --threshold 100"),
        ("Output looks all black or all white",
         "You're viewing a 16-bit TIF in a standard viewer.",
         "Use the PNG preview file, or open in ImageJ with Auto Brightness/Contrast."),
        ("Processing is very slow",
         "numba is not installed - Python fallback loops are used.",
         "Install numba for 10-100x speedup:\npip install numba"),
        ("'Could not load image' error",
         "The input file path is incorrect or the file doesn't exist.",
         "Check the path and ensure OpenCV can read the file format."),
        ("Display resolution doesn't match my panel",
         "Default resolution is 2412x2288.",
         "Specify your panel's resolution:\n"
         "python src/main.py --width YOUR_WIDTH --height YOUR_HEIGHT"),
        ("The crop region doesn't fit my image",
         "Default crop is set for a specific camera setup.",
         "Adjust crop coordinates or disable cropping:\n"
         "python src/main.py --no-crop"),
    ]

    for question, cause, fix in issues:
        _add_heading(doc, f"Q: {question}", level=3)
        p = doc.add_paragraph()
        r = p.add_run("Cause: ")
        r.bold = True
        r.font.size = Pt(10)
        r = p.add_run(cause)
        r.font.size = Pt(10)

        p2 = doc.add_paragraph()
        r = p2.add_run("Fix: ")
        r.bold = True
        r.font.size = Pt(10)
        r = p2.add_run(fix)
        r.font.size = Pt(10)
        r.font.name = 'Consolas' if '\n' in fix else 'Calibri'
        doc.add_paragraph()  # spacing

    # Footer
    doc.add_paragraph()
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run("ROI Algorithm Pipeline v1.0.0 - Internal use only - Meta Platforms, Inc.")
    r.font.size = Pt(9)
    r.font.italic = True
    r.font.color.rgb = RGBColor(0x99, 0x99, 0x99)


def create_user_manual():
    """Create the complete Word document user manual."""
    print("Creating Word Document User Manual...")
    doc = Document()

    # Page setup
    section = doc.sections[0]
    section.page_width = Cm(21)
    section.page_height = Cm(29.7)
    section.top_margin = Cm(2.5)
    section.bottom_margin = Cm(2.5)
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.5)

    # Build all sections
    build_title_page(doc)
    build_toc(doc)
    build_section1(doc)
    build_section2(doc)
    build_section3(doc)
    build_section4(doc)
    build_section5(doc)
    build_section6(doc)
    build_section7(doc)
    build_section8(doc)
    build_section9(doc)

    # Save
    doc_path = DOCS_DIR / "ROI_Algorithm_User_Manual.docx"
    doc.save(str(doc_path))
    print(f"\nDOCX saved: {doc_path}")
    return str(doc_path)


if __name__ == "__main__":
    create_user_manual()
