# -*- coding: utf-8 -*-
"""
PowerPoint (PPTX) User Manual Generator for ROI Algorithm Pipeline.
Uses images from docs/images/ (generated by generate_images.py).

Usage:
    python docs/create_user_manual_ppt.py

Requires:
    pip install python-pptx
"""
import sys
from pathlib import Path

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN
except ImportError:
    print("Error: python-pptx is required. Install with: pip install python-pptx")
    sys.exit(1)

DOCS_DIR = Path(__file__).parent
IMG_DIR = DOCS_DIR / "images"

BLUE = RGBColor(0x00, 0x3C, 0x71)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
GRAY = RGBColor(0x33, 0x33, 0x33)
LIGHT_BLUE = RGBColor(0xBB, 0xDE, 0xFB)
MED_BLUE = RGBColor(0x90, 0xCA, 0xF9)
SKY_BLUE = RGBColor(0x64, 0xB5, 0xF6)


def _bg(slide, color):
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = color


def _text(slide, left, top, width, height, text, size=18, bold=False,
          color=GRAY, align=PP_ALIGN.LEFT):
    tb = slide.shapes.add_textbox(Inches(left), Inches(top),
                                  Inches(width), Inches(height))
    tf = tb.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(size)
    p.font.bold = bold
    p.font.color.rgb = color
    p.font.name = "Calibri"
    p.alignment = align
    return tb


def _bullets(slide, left, top, width, height, lines, size=12, color=GRAY):
    tb = slide.shapes.add_textbox(Inches(left), Inches(top),
                                  Inches(width), Inches(height))
    tf = tb.text_frame
    tf.word_wrap = True
    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = line
        p.font.size = Pt(size)
        p.font.color.rgb = color
        p.font.name = "Calibri"
        p.space_after = Pt(3)
    return tb


def _img(slide, name, left, top, width=None, height=None):
    path = IMG_DIR / name
    if not path.exists():
        _text(slide, left, top, 4, 0.5, f"[Missing: {name}]", size=10,
              color=RGBColor(0xFF, 0, 0))
        return None
    kw = {}
    if width:
        kw['width'] = Inches(width)
    if height:
        kw['height'] = Inches(height)
    return slide.shapes.add_picture(str(path), Inches(left), Inches(top), **kw)


def create_user_manual_ppt():
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    blank = prs.slide_layouts[6]

    # ── Slide 1: Title ──
    s = prs.slides.add_slide(blank)
    _bg(s, BLUE)
    _text(s, 1, 1.2, 11, 1.5, "ROI Algorithm Pipeline",
          size=44, bold=True, color=WHITE, align=PP_ALIGN.CENTER)
    _text(s, 1, 2.8, 11, 1, "User Manual",
          size=36, color=LIGHT_BLUE, align=PP_ALIGN.CENTER)
    _text(s, 1, 4.2, 11, 1,
          "Display Panel Image Processing \u2014 Step-by-Step Guide",
          size=20, color=MED_BLUE, align=PP_ALIGN.CENTER)
    _text(s, 1, 5.5, 11, 0.5,
          "Version 1.0.0  |  MR Display Hardware Team  |  Byung Geun Jun",
          size=14, color=SKY_BLUE, align=PP_ALIGN.CENTER)

    # ── Slide 2: What is This Tool? ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8, "What is This Tool?",
          size=32, bold=True, color=BLUE)
    _bullets(s, 0.5, 1.3, 6, 5.5, [
        "A Python-based image processing pipeline for",
        "display panel analysis.",
        "",
        "Input:  Camera image of display panel (16-bit TIF)",
        "Output: Normalized image at display-pixel resolution",
        "",
        "\u25a0 Key Features:",
        "  \u2022 Automatic ROI Detection",
        "  \u2022 Pixel Value Preservation (INTER_NEAREST)",
        "  \u2022 Area-Sum Resize (every pixel contributes)",
        "  \u2022 16-bit Output (full dynamic range)",
        "  \u2022 Modular Design (each step independent)",
    ], size=13)
    _img(s, "step6_summary.png", 7, 1.3, width=6)

    # ── Slide 3: Installation ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8, "Installation",
          size=32, bold=True, color=BLUE)
    _bullets(s, 0.5, 1.3, 5.5, 5.5, [
        "\u25a0 Prerequisites:",
        "  \u2022 Python 3.8+",
        "  \u2022 Windows, macOS, or Linux",
        "",
        "\u25a0 Step 1: Install Dependencies",
        "  cd 20260304_ROI_algorithm",
        "  pip install -r requirements.txt",
        "",
        "\u25a0 Step 2: Optional (Faster Processing)",
        "  pip install numba",
        "",
        "\u25a0 Required Packages:",
        "  numpy, opencv-python, matplotlib,",
        "  scipy, pillow",
    ], size=12)
    _bullets(s, 6.5, 1.3, 6.3, 5.5, [
        "\u25a0 Project Structure:",
        "",
        "20260304_ROI_algorithm/",
        "\u251c\u2500 src/               # Core modules",
        "\u2502  \u251c\u2500 1_utils.py      # Utilities",
        "\u2502  \u251c\u2500 2_roi_detector.py  # ROI detection",
        "\u2502  \u251c\u2500 3_image_cropper.py # Image crop",
        "\u2502  \u251c\u2500 4_perspective_warper.py",
        "\u2502  \u251c\u2500 5_area_sum_resizer.py",
        "\u2502  \u251c\u2500 6_image_normalizer.py",
        "\u2502  \u251c\u2500 7_display_panel_processor.py",
        "\u2502  \u2514\u2500 main.py         # CLI entry",
        "\u251c\u2500 data/              # Input images",
        "\u251c\u2500 output/            # Results",
        "\u2514\u2500 requirements.txt",
    ], size=11)

    # ── Slide 4: Quick Start ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8, "Quick Start Guide",
          size=32, bold=True, color=BLUE)
    _bullets(s, 0.5, 1.2, 6, 5.5, [
        "\u25a0 Run with Default Settings:",
        "  python src/main.py",
        "",
        "  Processes data/G32_cal.tif \u2192 output/",
        "",
        "\u25a0 Custom Input/Output:",
        "  python src/main.py --input path/to/image.tif",
        "  python src/main.py --output results/",
        "",
        "\u25a0 Custom Display Resolution:",
        "  python src/main.py --width 1920 --height 1080",
        "",
        "\u25a0 Adjust Threshold:",
        "  python src/main.py --threshold 100",
        "",
        "\u25a0 Skip Cropping:",
        "  python src/main.py --no-crop",
    ], size=12)
    _bullets(s, 6.8, 1.2, 6, 5.5, [
        "\u25a0 Expected Console Output:",
        "",
        "==================================",
        "Display Panel Processing Pipeline",
        "==================================",
        "[Step 1] Loading image...",
        "  Original: 14144 x 10640 pixels",
        "[Step 2] Cropping image...",
        "  Cropped: 10000 x 9600 pixels",
        "[Step 3] Detecting ROI...",
        "  ROI: 9374 x 8894 pixels",
        "  Tilt angle: -0.03 degrees",
        "[Step 4] Perspective warp...",
        "[Step 5] Resizing to 2412x2288...",
        "[Step 6] Normalizing to 16-bit...",
        "Processing Complete!",
    ], size=11)

    # ── Slide 5: Pipeline Overview ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8, "Pipeline Overview",
          size=32, bold=True, color=BLUE)
    _bullets(s, 0.5, 1.2, 5.5, 5.5, [
        "End-to-End Pipeline Flow:",
        "",
        "Step 0: Load Original Image",
        "  \u2022 Read 16-bit TIF image",
        "",
        "Step 1: Image Cropping",
        "  \u2022 Remove unnecessary border regions",
        "",
        "Step 2: ROI Detection",
        "  \u2022 Binarize \u2192 Morphology \u2192 Contour \u2192 Corners",
        "",
        "Step 3: Perspective Correction",
        "  \u2022 4-corner perspective transform",
        "",
        "Step 4: Area-Sum Resize",
        "  \u2022 Camera \u2192 Display resolution",
        "",
        "Step 5: Normalization",
        "  \u2022 Normalize to 16-bit (0\u201365535)",
    ], size=12)
    _img(s, "step6_arch.png", 6.5, 1.2, width=6.3)

    # ── Slide 6: Step 0 Original ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Step 0: Load Original Image", size=28, bold=True, color=BLUE)
    _bullets(s, 0.5, 1.2, 5, 2.5, [
        "\u25a0 Module: src/1_utils.py",
        "  \u2022 Load 16-bit TIF via cv2.imread()",
        "",
        "\u25a0 Input: data/G32_cal.tif",
        "  \u2022 Mono camera capture",
        "  \u2022 14144 x 10640 pixels, uint16",
    ], size=12)
    _img(s, "step0_original.png", 5.8, 1.0, width=7)

    # ── Slide 7: Step 0 Histogram ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Step 0: Image Analysis \u2014 Histogram",
          size=28, bold=True, color=BLUE)
    _img(s, "step0_histogram.png", 0.5, 1.2, width=12)
    _bullets(s, 0.5, 5.8, 12, 1.5, [
        "\u2022 Histogram: background (low) vs display (high)",
        "\u2022 Red dashed line: ROI detection threshold (=50)",
        "\u2022 Tip: Choose threshold in valley between peaks",
    ], size=12)

    # ── Slide 8: Step 1 Crop ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Step 1: Image Cropping", size=28, bold=True, color=BLUE)
    _img(s, "step1_crop.png", 0.3, 1.2, width=12.5)
    _bullets(s, 0.5, 5.5, 12, 2, [
        "\u25a0 Classes: ImageCropper + CropRegion (src/3_image_cropper.py)",
        "  \u2022 Crop: (1700, 300) \u2192 (11700, 9900)  |  14144\u00d710640 \u2192 10000\u00d79600",
        "\u25a0 Code:  cropper = ImageCropper(CropRegion(1700, 300, 11700, 9900))",
        "        cropped = cropper.crop(image)",
    ], size=12)

    # ── Slide 9: Step 2 Binary ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Step 2: ROI Detection \u2014 Binarization",
          size=24, bold=True, color=BLUE)
    _img(s, "step2_binary.png", 0.3, 1.2, width=12.5)
    _bullets(s, 0.5, 5.3, 12, 2, [
        "\u25a0 Class: ROIDetector (src/2_roi_detector.py)",
        "  1) Binarize: pixel > 50 \u2192 white  |  2) Morph Close (51\u00d751)  |  "
        "3) Morph Open  |  4) Hole fill",
    ], size=12)

    # ── Slide 10: Step 2 Corners ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Step 2: ROI Detection \u2014 Corners",
          size=24, bold=True, color=BLUE)
    _img(s, "step2_corners.png", 0.3, 1.1, width=8.5)
    _img(s, "step2_table.png", 9.0, 1.1, width=4)
    _bullets(s, 0.5, 5.3, 12, 2, [
        "\u25a0 findContours \u2192 largest contour \u2192 minAreaRect \u2192 4 corners (TL,TR,BR,BL)",
        "\u25a0 Code:  roi = ROIDetector(threshold=50).detect(cropped)",
        "        print(roi.corners, roi.angle, roi.width, roi.height)",
    ], size=12)

    # ── Slide 11: Step 3 Warp ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Step 3: Perspective Correction",
          size=28, bold=True, color=BLUE)
    _img(s, "step3_warp.png", 0.3, 1.1, width=8)
    _bullets(s, 8.5, 1.2, 4.5, 3.5, [
        "\u25a0 PerspectiveWarper",
        "  (src/4_perspective_warper.py)",
        "",
        "  1) Map 4 corners \u2192 rectangle",
        "  2) getPerspectiveTransform()",
        "  3) warpPerspective()",
        "",
        "\u25a0 INTER_NEAREST:",
        "  \u2022 Preserves pixel values",
        "  \u2022 No blending/smoothing",
        "  \u2022 Critical for measurements",
    ], size=11)

    # ── Slide 12: Step 3 Matrix ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Step 3: Transform Matrix Details",
          size=28, bold=True, color=BLUE)
    _img(s, "step3_matrix.png", 1.5, 1.2, width=10)
    _bullets(s, 0.5, 5.5, 12, 1.5, [
        "\u2022 3\u00d73 homography: tilted quad \u2192 axis-aligned rect",
        "\u2022 Code:  warped = PerspectiveWarper(cv2.INTER_NEAREST)"
        ".warp(cropped, roi.corners).image",
    ], size=12)

    # ── Slide 13: Step 4 Resize ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Step 4: Area-Sum Resize",
          size=28, bold=True, color=BLUE)
    _img(s, "step4_resize.png", 0.3, 1.1, width=12.5)
    _bullets(s, 0.5, 5.3, 12, 2, [
        "\u25a0 AreaSumResizer (src/5_area_sum_resizer.py)",
        "  \u2022 Camera \u2192 Display resolution  |  Each pixel = mean of ~3.89\u00d73.89 camera px",
        "\u25a0 Code:  result = AreaSumResizer().resize(warped, (2412, 2288))",
    ], size=12)

    # ── Slide 14: Step 4 Concept ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Step 4: Area-Sum Resize \u2014 How It Works",
          size=28, bold=True, color=BLUE)
    _img(s, "step4_concept.png", 0.3, 1.1, width=7)
    _bullets(s, 7.5, 1.2, 5.3, 5, [
        "\u25a0 Principle:",
        "  1 display pixel = ~3.89\u00d73.89 camera px",
        "  Output = weighted MEAN of all camera",
        "  pixels in the corresponding area",
        "",
        "\u25a0 Why not bilinear/bicubic?",
        "  \u2022 Standard resize ALTERS values",
        "  \u2022 Area-Sum PRESERVES light energy",
        "  \u2022 Essential for precise measurement",
        "",
        "\u25a0 Fractional boundaries:",
        "  weight = overlap_area / pixel_area",
    ], size=11)

    # ── Slide 15: Step 4 Zoom ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Step 4: Zoom \u2014 Camera vs Display Pixels",
          size=24, bold=True, color=BLUE)
    _img(s, "step4_zoom.png", 0.3, 1.1, width=12.5)
    _bullets(s, 0.5, 5.5, 12, 1.5, [
        "\u2022 Left: Warped center 100\u00d7100 (camera pixels visible)",
        "\u2022 Right: Resized center 30\u00d730 (each = one display pixel)",
    ], size=12)

    # ── Slide 16: Step 5 Normalize ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Step 5: 16-bit Normalization",
          size=28, bold=True, color=BLUE)
    _img(s, "step5_norm.png", 0.3, 1.1, width=12.5)
    _bullets(s, 0.5, 6.0, 12, 1, [
        "\u25a0 Formula: out = (px - min)/(max - min) \u00d7 65535  |  "
        "Code: ImageNormalizer(16).normalize(resized).image",
    ], size=12)

    # ── Slide 17: Config ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8, "Configuration Reference",
          size=32, bold=True, color=BLUE)
    _bullets(s, 0.5, 1.2, 6, 5.5, [
        "\u25a0 CLI Options:",
        "  --input/-i     Input image (data/G32_cal.tif)",
        "  --output/-o    Output dir (output)",
        "  --width/-W     Display width (2412)",
        "  --height/-H    Display height (2288)",
        "  --threshold/-t ROI threshold (50)",
        "  --crop-x-start (1700)",
        "  --crop-y-start (300)",
        "  --crop-x-end   (11700)",
        "  --crop-y-end   (9900)",
        "  --no-crop      Disable cropping",
        "  --no-intermediates  Skip intermediates",
        "",
        "\u25a0 Threshold Guide:",
        "  30-50:   Dim panels",
        "  50-100:  Standard (default)",
        "  100-200: Bright panels",
        "  200+:    Very bright / noisy bg",
    ], size=11)
    _bullets(s, 7, 1.2, 6, 5.5, [
        "\u25a0 Python API Config:",
        "",
        "  from src import ProcessingConfig",
        "",
        "  config = ProcessingConfig(",
        "      crop_x_start=1700,",
        "      crop_y_start=300,",
        "      crop_x_end=11700,",
        "      crop_y_end=9900,",
        "      use_crop=True,",
        "      roi_threshold=50,",
        "      morph_kernel_size=51,",
        "      display_width=2412,",
        "      display_height=2288,",
        "      output_bit_depth=16,",
        "      save_intermediates=True",
        "  )",
    ], size=11)

    # ── Slide 18: API Full Pipeline ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Python API \u2014 Full Pipeline", size=28, bold=True, color=BLUE)
    _bullets(s, 0.5, 1.2, 12, 5.5, [
        "from src import DisplayPanelProcessor, ProcessingConfig",
        "",
        "config = ProcessingConfig(display_width=2412, display_height=2288)",
        "processor = DisplayPanelProcessor(config)",
        'result = processor.process("data/G32_cal.tif")',
        "",
        'processor.save_results(result, "output/")',
        'processor.save_visualization(result, "output/")',
        "",
        '# Access intermediate results',
        'print(f"Original:   {result.original_image.shape}")    # (10640, 14144)',
        'print(f"Cropped:    {result.cropped_image.shape}")     # (9600, 10000)',
        'print(f"Warped:     {result.warped_image.shape}")      # (8894, 9374)',
        'print(f"Resized:    {result.resized_image.shape}")     # (2288, 2412)',
        'print(f"Normalized: {result.normalized_image.shape}")  # (2288, 2412)',
        'print(f"Tilt angle: {result.stats[\'tilt_angle\']:.4f}\u00b0")',
    ], size=12)

    # ── Slide 19: API Individual ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8,
          "Python API \u2014 Individual Modules",
          size=28, bold=True, color=BLUE)
    _bullets(s, 0.5, 1.2, 6, 5.5, [
        "import cv2",
        "from src import (",
        "    ImageCropper, CropRegion,",
        "    ROIDetector, PerspectiveWarper,",
        "    AreaSumResizer, ImageNormalizer",
        ")",
        "",
        '# Load',
        'img = cv2.imread("data/G32_cal.tif",',
        "                  cv2.IMREAD_UNCHANGED)",
        "",
        "# 1. Crop",
        "cropped = ImageCropper(",
        "    CropRegion(1700,300,11700,9900)",
        ").crop(img)",
        "",
        "# 2. Detect ROI",
        "roi = ROIDetector(threshold=50)",
        "      .detect(cropped)",
    ], size=11)
    _bullets(s, 6.8, 1.2, 6, 5.5, [
        "# 3. Perspective warp",
        "warped = PerspectiveWarper(",
        "    cv2.INTER_NEAREST",
        ").warp(cropped, roi.corners).image",
        "",
        "# 4. Area-sum resize",
        "resized = AreaSumResizer().resize(",
        "    warped, (2412, 2288)).image",
        "",
        "# 5. Normalize to 16-bit",
        "final = ImageNormalizer(",
        "    bit_depth=16",
        ").normalize(resized).image",
        "",
        "# Save output",
        'cv2.imwrite("final.tif", final)',
    ], size=11)

    # ── Slide 20: Output Files ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8, "Output Files",
          size=32, bold=True, color=BLUE)
    _bullets(s, 0.5, 1.3, 12, 3, [
        "\u25a0 Generated Files in output/:",
        "  00_cropped_image.tif            Cropped region (16-bit TIF)",
        "  04_warped_image.tif             Perspective-corrected (16-bit TIF)",
        "  05_resized_image.tif            Area-sum resized (16-bit TIF)",
        "  06_final_normalized.tif         Main output (16-bit TIF)",
        "  06_final_normalized_preview.png 8-bit preview (PNG)",
        "  06_final_comparison.png         Side-by-side comparison (PNG)",
    ], size=12)
    _bullets(s, 0.5, 4.2, 12, 3, [
        "\u25a0 How to View 16-bit TIF Files:",
        "  \u2022 ImageJ/FIJI: Open \u2192 Adjust \u2192 Brightness/Contrast \u2192 Auto",
        '  \u2022 Python: cv2.imread("file.tif", cv2.IMREAD_UNCHANGED)',
        "  \u2022 MATLAB: imread('file.tif')",
        "  \u2022 Quick view: Use PNG preview (06_final_normalized_preview.png)",
        "",
        "  Note: 16-bit TIF appears black/white in standard viewers. This is normal.",
    ], size=11)

    # ── Slide 21: Pipeline Summary ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8, "Full Pipeline Summary",
          size=32, bold=True, color=BLUE)
    _img(s, "step6_summary.png", 0.3, 1.2, width=12.5)
    _bullets(s, 0.5, 4.5, 12, 2.5, [
        "Original \u2192 Crop \u2192 ROI Detect \u2192 Warp \u2192 Area-Sum Resize \u2192 16-bit Normalize",
        "",
        "\u25a0 Key Design Principles:",
        "  \u2022 INTER_NEAREST: Preserves original pixel values (measurement accuracy)",
        "  \u2022 Area-Sum resize: Every camera pixel contributes to the output",
        "  \u2022 Modular OOP: Each step = independent class, orchestrated by DisplayPanelProcessor",
    ], size=13)

    # ── Slide 22: Troubleshooting ──
    s = prs.slides.add_slide(blank)
    _text(s, 0.5, 0.3, 12, 0.8, "Troubleshooting & FAQ",
          size=32, bold=True, color=BLUE)
    _bullets(s, 0.5, 1.3, 6, 5.5, [
        '\u25a0 "No ROI detected" error',
        "  Cause: Threshold too high or too low",
        "  Fix: Try --threshold 30 or --threshold 100",
        "",
        "\u25a0 Output looks all black/white",
        "  Cause: Viewing 16-bit TIF in standard viewer",
        "  Fix: Use PNG preview or open in ImageJ",
        "",
        "\u25a0 Processing is very slow",
        "  Cause: numba not installed",
        "  Fix: pip install numba (10-100x speedup)",
    ], size=12)
    _bullets(s, 7, 1.3, 6, 5.5, [
        '\u25a0 "Could not load image" error',
        "  Cause: Invalid file path",
        "  Fix: Check path exists and is a valid image",
        "",
        "\u25a0 Wrong display resolution",
        "  Fix: --width YOUR_W --height YOUR_H",
        "",
        "\u25a0 Crop region doesn't fit",
        "  Fix: --no-crop or set custom crop coords:",
        "  --crop-x-start 0 --crop-y-start 0",
        "  --crop-x-end 5000 --crop-y-end 5000",
        "",
        "\u25a0 Tilt angle seems wrong",
        "  Fix: Adjust morph_kernel_size in Python API",
    ], size=12)

    # ── Slide 23: Thank You ──
    s = prs.slides.add_slide(blank)
    _bg(s, BLUE)
    _text(s, 1, 2.5, 11, 1.5, "Thank You",
          size=48, bold=True, color=WHITE, align=PP_ALIGN.CENTER)
    _text(s, 1, 4.2, 11, 1,
          "ROI Algorithm Pipeline \u2014 User Manual",
          size=20, color=LIGHT_BLUE, align=PP_ALIGN.CENTER)
    _text(s, 1, 5.2, 11, 0.5,
          "MR Display Hardware Team  |  Byung Geun Jun",
          size=14, color=MED_BLUE, align=PP_ALIGN.CENTER)
    _text(s, 1, 5.8, 11, 0.5,
          "For questions, contact byungpaul@meta.com",
          size=12, color=SKY_BLUE, align=PP_ALIGN.CENTER)

    # ── Save ──
    ppt_path = DOCS_DIR / "ROI_Algorithm_User_Manual.pptx"
    prs.save(str(ppt_path))
    print(f"\nPPT saved: {ppt_path}")
    return str(ppt_path)


if __name__ == "__main__":
    create_user_manual_ppt()
